name: Update Plugins and Datapacks

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download and Update Plugins
      run: |
        # Create the plugins directory if it doesn't exist
        mkdir -p plugins
        
        # List of plugin URLs (Manually add them here)
        declare -A plugin_urls=(
          ["https://cdn.modrinth.com/data/1u6JkXh5/versions/lynJ1VTU/worldedit-bukkit-7.3.9-beta-01-dist.jar"]="WorldEdit.jar"
          ["https://cdn.modrinth.com/data/DKY9btbd/versions/r9yT7tvE/worldguard-bukkit-7.0.13-beta-1-dist.jar"]="WorldGuard.jar"
          ["https://cdn.modrinth.com/data/lDAFcnRN/versions/Ou3efpX9/BackpackPlus-1.4.4.jar"]="BackpackPlus.jar"
          ["https://cdn.modrinth.com/data/djIh90x5/versions/6zcEqLZC/BannedWordsEffective-0.2.jar"]="BannedWordsEffective.jar"
          ["https://cdn.modrinth.com/data/21piUJ3H/versions/rUMsHDCO/DeathLocation-1.4.jar"]="DeathLocation.jar"
          ["https://cdn.modrinth.com/data/xfelWIYh/versions/HMjnq4s6/Discord-Linker-3.5.1.jar"]="DiscordLinker.jar"
          ["https://github.com/EssentialsX/Essentials/releases/download/2.20.1/EssentialsX-2.20.1.jar"]="EssentialsX.jar"
          ["https://github.com/EssentialsX/Essentials/releases/download/2.20.1/EssentialsXChat-2.20.1.jar"]="EssentialsXChat.jar"
          ["https://github.com/EssentialsX/Essentials/releases/download/2.20.1/EssentialsXSpawn-2.20.1.jar"]="EssentialsXSpawn.jar"
          ["https://cdn.modrinth.com/data/8J9TtDyT/versions/YlQ5grB2/FarmProtect-1.0.jar"]="FarmProtect.jar"
          ["https://cdn.modrinth.com/data/bZMr4QSx/versions/J6PRYzQS/GodItems-3.0.1.jar"]="GodItems.jar"
          ["https://cdn.modrinth.com/data/kbERwJ64/versions/Js79ZyIY/HomePlugin-0.6.4.jar"]="HomePlugin.jar"
          ["https://cdn.modrinth.com/data/l8Uv7FzS/versions/vsWM2O9Q/lifestealz-2.7.2.jar"]="LifeStealz.jar"
          ["https://cdn.modrinth.com/data/PhGsxDZn/versions/xPlVsiLO/loginop-1.0-SNAPSHOT.jar"]="LoginOP.jar"
          ["https://cdn.modrinth.com/data/3wmN97b8/versions/bTaKJxBv/multiverse-core-4.3.15-pre.1.jar"]="MultiverseCore.jar"
          ["https://github.com/playit-cloud/playit-minecraft-plugin/releases/latest/download/playit-minecraft-plugin.jar"]="PlayitGG.jar"
          ["https://cdn.modrinth.com/data/ecVvYtj3/versions/zjQoKxad/PowerRanks.jar"]="PowerRanks.jar"
          ["https://github.com/SkinsRestorer/SkinsRestorer/releases/download/15.4.4/SkinsRestorer.jar"]="SkinsRestorer.jar"
          ["https://cdn.modrinth.com/data/Kt3eUOUy/versions/93CEj3T6/Sleeper.jar"]="Sleeper.jar"
          ["https://cdn.modrinth.com/data/YrkmSvXh/versions/Va47sosG/TreeFeller-1.24.2.jar"]="TreeFeller.jar"
          ["https://cdn.modrinth.com/data/OhduvhIc/versions/ED8c5gtJ/veinminer-paper-2.2.1.jar"]="VeinMiner.jar"
          ["https://cdn.modrinth.com/data/P1OZGk5p/versions/EfNp6SMH/ViaVersion-5.1.2-SNAPSHOT.jar"]="ViaVersion.jar"
          ["https://cdn.modrinth.com/data/NpvuJQoq/versions/rtmgheCA/ViaBackwards-5.1.2-SNAPSHOT.jar"]="ViaBackwards.jar"
          ["https://modrinth.com/plugin/viarewind/version/4.0.4-SNAPSHOT+213"]="ViaRewind.jar"
        )
        
        # Loop through each plugin URL and download it with the correct name
        for url in "${!plugin_urls[@]}"; do
          wget -O "plugins/${plugin_urls[$url]}" "$url"
        done

    - name: Download and Update Datapacks
      run: |
        # Create the datapacks directory if it doesn't exist
        mkdir -p datapacks
        
        # List of datapack URLs (Manually add them here)
        declare -A datapack_urls=(
          ["https://cdn.modrinth.com/data/C36CZGrl/versions/Twg0nMqA/1.0.0-better_maces-dtpk-1.21.2-1.21.3.zip"]="BetterMaces.zip"
          ["https://cdn.modrinth.com/data/lIONMg0U/versions/eUdcrNwY/Better%20Multishot.zip"]="BetterMultishot.zip"
          ["https://cdn.modrinth.com/data/GWFnD2zx/versions/pU2rtKHz/ArmorStandArms-%5B1.21%5D-v.2.4.0.zip"]="ArmorStandArms.zip"
          ["https://cdn.modrinth.com/data/tpehi7ww/versions/8o3mS993/Dungeons%20and%20Taverns%20v4.5.zip"]="DungeonsAndTaverns.zip"
          ["https://cdn.modrinth.com/data/8Dbnvm77/versions/mmb8Om1D/DnT%20Nether%20Fortress%20Overhaul%20v2.5.zip"]="DnTNetherFortressOverhaul.zip"
          ["https://cdn.modrinth.com/data/glYcmYBi/versions/6a8KWZ7I/Drop%20Head%202.0%20%281.14-1.21.3%29.zip"]="DropHead.zip"
          ["https://cdn.modrinth.com/data/1NnAVIR5/versions/dSJDosLv/JJThunder_To_The_Max_1.21.0-1.21.1_v0.4.0.zip"]="JJThunderToTheMax.zip"
          ["https://cdn.modrinth.com/data/sk4iFZGy/versions/L5lkBuqD/Remove_Terralith_Intro_Message_v1.1.zip"]="RemoveTerralithIntroMessage.zip"
          ["https://cdn.modrinth.com/data/M185nxi6/versions/xmbECuEZ/Ships%203.0.3.zip"]="Ships.zip"
          ["https://cdn.modrinth.com/data/8oi3bsk5/versions/tnavs2WP/Terralith_1.21_v2.5.6.zip"]="Terralith.zip"
          ["https://cdn.modrinth.com/data/CVBAErky/versions/f8kEK0IG/%5BUniversal%5Dimst-v2.2.0.zip"]="ImstUniversal.zip"
          ["https://cdn.modrinth.com/data/6vWz8dzn/versions/SlrKw2lM/qrafty%27s-japanese-villages.zip"]="JapaneseVillages.zip"
          ["https://cdn.modrinth.com/data/qSvzu3X3/versions/x76egZTA/qrafty%27s-jungle_villages.zip"]="JungleVillages.zip"
          ["https://cdn.modrinth.com/data/KSQGzV5B/versions/vwwhdwEl/qrafty%27s-bamboo-villages.zip"]="BambooVillages.zip"
          ["https://cdn.modrinth.com/data/cqNgIqx3/versions/aVLcqNC4/qrafty%27s-mangrove-villages.zip"]="MangroveVillages.zip"
          ["https://cdn.modrinth.com/data/xlB8CNvE/versions/asGLAxZJ/qrafty%27s-underground-villages.zip"]="UndergroundVillages.zip"
          ["https://cdn.modrinth.com/data/5hXlgCAz/versions/GjZruQJm/qrafty%27s-dig-sites.zip"]="DigSites.zip"
          ["https://cdn.modrinth.com/data/rzcwdD7B/versions/MowmWuD2/qrafty%27s-mushroom-villages.zip"]="MushroomVillages.zip"
          ["https://cdn.modrinth.com/data/TrPmg4ei/versions/CFqYIKTD/qraftyfied-INDUSTRIAL.zip"]="Industrial.zip"
          ["https://cdn.modrinth.com/data/lWDHr9jE/versions/J5CxwkWM/tectonic-datapack-v2.4.0a.zip"]="TectonicDatapack.zip"
          ["https://cdn.modrinth.com/data/EEIwvQVo/versions/HbNg7Lhz/tidal_towns_1_21.zip"]="TidalTowns.zip"
          ["https://modrinth.com/datapack/terratonic/version/3.2"]="Terratonic.zip"
        )
        
        # Loop through each datapack URL and download it with the correct name
        for url in "${!datapack_urls[@]}"; do
          wget -O "datapacks/${datapack_urls[$url]}" "$url"
        done

    - name: Commit and Push Changes
      run: |
        # Check if any files were updated
        if [[ $(git status --porcelain) ]]; then
          git add plugins/ datapacks/
          git commit -m "Auto-update plugins and datapacks with clean names"
          git push
        else
          echo "No changes to commit"
        fi
